【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

＜計算式＞
AB = Cとすると

$c_{ik}$ = $\sum_{ j = 0 }^{ 2 } a_{ij}b_{jk}$
という計算となるので
AB = [[6, 29, -20],
         [12, 52, 38],
         [-18, -51, -48]]


【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

In [10]:
import numpy as np
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(A@B)
print(np.matmul(A, B))
print(A.dot(B))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。

行列Aの(0,0)の要素 
a
0
,
0
 と行列Bの(0,0)の要素 
b
0
,
0
 を掛け合わせる
行列Aの(0,1)の要素 
a
0
,
1
 と行列Bの(1,0)の要素 
b
1
,
0
 を掛け合わせる
行列Aの(0,2)の要素 
a
0
,
2
 と行列Bの(2,0)の要素 
b
2
,
0
 を掛け合わせる
それらの値を全て足し合わせる
数式で表すと

2
∑
k
=
0
 
a
0
,
k
b
k
,
0
です。

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

計算結果である 
3
×
3
 の行列Cの各要素 
c
i
,
j
 は数式で表すと次のようになります。

c
i
,
j
=
2
∑
k
=
0
 
a
i
,
k
b
k
,
j
for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス 
i
 や 
j
 を1増やすと、次の行や列に移ることができます。
 
 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [18]:
def mat_calc(A, B):
    """
    ２つの行列積の計算を行う関数
    定義にあわず計算不可な時はエラーメッセージを表示する。
    
    パラメーター
    ーーーーーーーーーー
    A、B : 配列
        計算対象となる配列を引数に指定
    
    戻り値
    ーーーーーーーーーー
    計算可能の場合
    calc_list_ndarray : 配列
        計算結果の配列を返す
    
    計算不可の場合
    エラーメッセージを表示
    
    """
    calc_list = []
    ah = len(A)
    aw = len(A[0])
    bh = len(B)
    bw = len(B[0])
    if aw == bh:
        for i in range(ah):
            for k in range(bw):
                total = 0
                for j in range(aw):
                    calc = A[i][j]*B[j][k]
                    total += calc
                calc_list.append(total)

        calc_list_ndarray = np.array(calc_list)
        calc_list_ndarray = calc_list_ndarray.reshape(ah, bw)
        return calc_list_ndarray
    else:
        print("※警告：積の左側の列の次元と右側の行の次元が一致しないため、計算できません。確認してください!")

In [19]:
mat_calc(A, B)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [20]:
D = np.array([[-1, 2, 3], [4, -5, 6]])
E = np.array([[-9, 8, 7], [6, -5, 4]])

In [21]:
mat_calc(D, E)

※注意：積の左側の列の次元と右側の行の次元が一致しないため、計算できません。確認してください!


【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [22]:
mat_calc(D, E.T)

array([[ 46,  -4],
       [-34,  73]])