# 【問題1】これまで利用してきたクラスの列挙

<br>pandas.DataFrame
<br>matplotlib.pyplot
<br>sklearn.linear_model.LogisticRegression

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

<br>メソッド　：　DataFrame. [head,sum, describe, info, mean]
<br>インスタンス変数　：　DataFrame. [ T, columns, blocks, dtype, loc]

# 【問題3】標準化クラスをスクラッチで作成

In [1]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """

    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            学習データ
        """
        import numpy as np
        self.mean_ = np.mean(X)
        self.var_ = np.std(X)

        return self

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        
        X_scaled = (X - self.mean_) / self.var_
        
        return X_scaled

In [3]:
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : 2.46
分散 : 1.781684596105607
[[ 1.48174374  0.58371723 -0.59494256 -1.26846245]
 [ 1.36949043  0.30308395 -0.59494256 -1.26846245]
 [ 1.25723711  0.41533726 -0.65106922 -1.26846245]
 [ 1.20111046  0.3592106  -0.53881591 -1.26846245]
 [ 1.42561708  0.63984389 -0.59494256 -1.26846245]
 [ 1.65012371  0.80822386 -0.42656259 -1.15620913]
 [ 1.20111046  0.52759057 -0.59494256 -1.21233579]
 [ 1.42561708  0.52759057 -0.53881591 -1.26846245]
 [ 1.08885714  0.24695729 -0.59494256 -1.26846245]
 [ 1.36949043  0.3592106  -0.53881591 -1.3245891 ]]


# 【問題4】 四則演算を行うクラスの作成

In [1]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
        return self.value
        
    def diff(self, value3):
        self.value -= value3
        return self.value 
    
    def multi(self, value4):
        self.value *= value4
        return self.value
    
    def divi(self, value5):
        self.value /=value5
        return self.value


In [3]:
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.diff(3)
print("value : {}".format(example.value))
example.multi(3)
print("value : {}".format(example.value))
example.divi(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8
value : 5
value : 15
value : 5.0
